config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'static_pages/index'
  
  resources :clients
  resources :projects do
    resources :tasks
  end
  resources :users
  resources :account_activations, only: [:edit]
 
  get    'login'   => 'sessions#new'
  get    'signup'  => 'users#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  root 'static_pages#index'
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_project, only: [:new, :show, :edit, :update, :destroy, :create]
  before_action :logged_in_user

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.project = @project

    respond_to do |format|
      if @task.save
        format.html { redirect_to @project, success: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @project, success: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to @project, success: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end
    
    def set_project
      @project = Project.find(params[:project_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:employee_name, :time, :date, :description)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<% if @task.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

    <ul>
    <% @task.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for([@project, @task], html: {class: 'form-horizontal'}) do |f| %>
  <fieldset>
    <div class="form-group">
      <%= f.label :employee_name, class: "col-lg-2 control-label" %><br>
      <div class="col-lg-10">
        <%= collection_select(:task, :employee_name, User.all, :name, :name, prompt: true) %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :time, class: "col-lg-2 control-label" %><br>
      <div class="col-lg-10">
        <%= f.number_field :time, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :date, class: "col-lg-2 control-label" %><br>
      <div class="col-lg-10">
        <%= f.date_select :date, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :description, class: "col-lg-2 control-label" %><br>
      <div class="col-lg-10">
        <%= f.text_area :description, class: "form-control" %>
      </div>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>


  </fieldset>

<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Employee name</th>
      <th>Time</th>
      <th>Date</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.employee_name %></td>
        <td><%= task.time %></td>
        <td><%= task.date %></td>
        <td><%= task.description %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', project_path(@project) %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee name:</strong>
  <%= @task.employee_name %>
</p>

<p>
  <strong>Time:</strong>
  <%= @task.time %>
</p>

<p>
  <strong>Date:</strong>
  <%= @task.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>