config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'static_pages/index'
  
  resources :clients
  resources :projects do
    resources :tasks
  end
  resources :users
  resources :account_activations, only: [:edit]
 
  get    'login'   => 'sessions#new'
  get    'signup'  => 'users#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  root 'static_pages#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :client
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user 

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_url, suceess: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_url, success: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, success: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :start_date, :end_date, :client_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for(@project, html: {class: 'form-horizontal'}) do |f| %>
  <fieldset>
    <div class="form-group">
      <%= f.label :title, class: "col-lg-2 control-label" %><br>
      <div class="col-lg-10">
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :description, class: "col-lg-2 control-label" %><br>
      <div class="col-lg-10">
      <%= f.text_area :description, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :start_date, class: "col-lg-2 control-label" %><br>
      <div class="col-lg-10">
      <%= f.date_select :start_date, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :end_date, class: "col-lg-2 control-label" %><br>
      <div class="col-lg-10">
      <%= f.date_select :end_date, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :client_id, class: "col-lg-2 control-label" %><br>
      <div class="col-lg-10">
        <%= collection_select(:project, :client_id, Client.all, :id, :name, prompt: true) %>
      </div>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </fieldset>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing Projects</h1>

<%= link_to 'New Project', new_project_path %>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Start date/End Date</th>
      <th>Client</th>
    </tr>
  </thead>

  <tbody id="projects">
    
  </tbody>
</table>

<img src='http://www.fostersystems.com/ccdata/images/spinner.gif' id='next_page_spinner' />

<%= javascript_include_tag 'pagination' %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div class="row">
  <h1><%= @project.title %></h1>
  <h3><%= @project.client.name %></h3>
</div>

<div class="row">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Description</h3>
    </div>
    <div class="panel-body">
        <%= @project.description %>
    </div>
  </div>
  <p>
    <strong>Start date:</strong> <%= @project.start_date %>
  </br>
    <strong>End date:</strong> <%= @project.end_date %>
  </p>
</div>

<div class="row">
  <%= link_to 'Edit Project', edit_project_path(@project) %> | <%= link_to 'Back', projects_path %> | <%= link_to 'New Task', new_project_task_path(@project.id) %>
</div>

<div class="row">
  <h3>Task log</h3> 
  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <th>Employee</th>
        <th>Hours</th>
        <th>Date</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      <% @project.tasks.each do |task| %>
      <tr>
        <td><%= task.employee_name %></td>
        <td><%= task.time %></td>
        <td><%= task.date %></td>
        <td><%= task.description %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>