config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'static_pages/index'
  
  resources :clients
  resources :projects do
    resources :tasks
  end
  resources :users
  resources :account_activations, only: [:edit]
 
  get    'login'   => 'sessions#new'
  get    'signup'  => 'users#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  root 'static_pages#index'
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Wolfie Books</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Projects', projects_path %> 
        </li>
        <li>
          <%= link_to 'Clients', clients_path %> 
        </li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li>
            <%= link_to "Log out", logout_path, method: "delete" %>
          </li>
        <% else %>
          <li>
            <%= link_to "Log in", login_path %>
          </li>
        <% end %>  
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WolfieBooks</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.0/handlebars.min.js"> </script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/nav' %>
  <div class="container">
	<% flash.each do |message_type, message| %>
	  <div class="alert alert-dismissible alert-<%= message_type %>">
	    <button type="button" class="close" data-dismiss="alert">×</button>
	    <%= message %>
	  </div>
	<% end %>
    <%= yield %>
  </div>

</body>
</html>